<script setup lang="ts">
/**
 * The drawer's answer to "where does this object's desired state live?".
 *
 * The panel is written to be believed only as far as it should be. Argo CD can
 * say with certainty that it manages an object, and it can say almost nothing
 * about which file in a repository declares it, and those are shown as two
 * different statements rather than blurred into one confident line.
 */
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'

import { api, message } from '@/api'
import { ManifestCertainty, OwnershipConfidence } from '@/types'
import type { GitSource, ManifestSearch, ResourceOwnership, ResourceRef } from '@/types'

const props = defineProps<{ clusterId: string; resource: ResourceRef }>()

const router = useRouter()

const ownership = ref<ResourceOwnership | null>(null)
const error = ref('')

const search = ref<ManifestSearch | null>(null)
const searching = ref(false)
const searchError = ref('')
const contentOpen = ref(false)

// Clicking down a list starts reads that finish out of order, and only the
// newest one is allowed to write its answer.
let token = 0

async function load() {
  const mine = ++token
  error.value = ''
  // A search belongs to the object it was run for. Carrying it to the next
  // row would name a file as somewhere else's desired state.
  search.value = null
  searchError.value = ''
  searching.value = false
  contentOpen.value = false
  try {
    const found = await api.gitOwnership(props.clusterId, props.resource)
    if (mine !== token) return
    ownership.value = found
  } catch (err) {
    if (mine !== token) return
    error.value = message(err)
    ownership.value = null
  }
}

watch(
  () => [props.clusterId, props.resource.kind, props.resource.namespace, props.resource.name],
  load,
  { immediate: true },
)

// A cluster that does not run Argo CD has no GitOps story, and a row saying so
// on every drawer would be noise rather than news.
const shown = computed(() => ownership.value?.installed === true)

const app = computed(() => ownership.value?.app ?? null)
const sources = computed(() => ownership.value?.sources ?? [])

const managed = computed(() => {
  const confidence = ownership.value?.confidence
  return (
    confidence === OwnershipConfidence.OwnershipTracked ||
    confidence === OwnershipConfidence.OwnershipConfirmed
  )
})

/**
 * headline is the one sentence the panel leads with.
 *
 * A candidate gets its own wording rather than a quieter colour, because an
 * engineer who reads "Managed by Argo CD" will go and edit a repository, and
 * the label is the only thing standing between a guess and that edit.
 */
const headline = computed(() => {
  switch (ownership.value?.confidence) {
    case OwnershipConfidence.OwnershipTracked:
    case OwnershipConfidence.OwnershipConfirmed:
      return { label: 'Managed by Argo CD', tone: 'text-ok' }
    case OwnershipConfidence.OwnershipCandidate:
      return { label: 'Possibly managed by Argo CD', tone: 'text-warn' }
    default:
      return { label: 'Unmanaged', tone: 'text-ink-muted' }
  }
})

/** certainty puts a word on how close to a file a source gets. */
function certainty(source: GitSource): string {
  switch (source.certainty) {
    case ManifestCertainty.ManifestExact:
      return 'Manifest located'
    case ManifestCertainty.ManifestTree:
      return 'Source tree known'
    case ManifestCertainty.ManifestGenerated:
      return `Generated by ${source.renderer}`
    default:
      return 'No manifests'
  }
}

/**
 * searchable says whether there is a file to go and look for.
 *
 * Only a directory of plain manifests has one. Helm, Kustomize and config
 * management plugins render their objects from templates, so no file in the
 * repository equals what is running, and offering a button that could only
 * come back empty would be worse than offering nothing.
 */
const searchable = computed(
  () =>
    managed.value &&
    sources.value.some((source) => source.certainty === ManifestCertainty.ManifestTree),
)

const located = computed(() => search.value?.located ?? null)
const candidates = computed(() => search.value?.candidates ?? [])

// Seven characters is how a commit is written down and said out loud, and the
// whole hash is on the clipboard of nobody who wanted it here.
const commit = computed(() => search.value?.commit?.slice(0, 7) ?? '')

/**
 * locate reads the repository.
 *
 * Deliberately behind a press rather than run when the drawer opens: the first
 * read of a repository clones it, and doing that to every row somebody clicks
 * through would make the list feel broken.
 */
async function locate() {
  const mine = token
  searching.value = true
  searchError.value = ''
  contentOpen.value = false
  try {
    const found = await api.locateManifest(props.clusterId, props.resource)
    if (mine !== token) return
    search.value = found
  } catch (err) {
    if (mine !== token) return
    searchError.value = message(err)
    search.value = null
  } finally {
    if (mine === token) searching.value = false
  }
}

function openApplication() {
  const target = app.value
  const kind = ownership.value?.appKind
  if (!target || !kind) return
  void router.push({
    name: 'resource',
    params: {
      clusterId: props.clusterId,
      kind,
      // "_" stands in for "no namespace": a cluster-scoped object still needs
      // a path segment.
      namespace: target.namespace || '_',
      name: target.name,
    },
  })
}
</script>

<template>
  <section v-if="shown || error">
    <h2 class="text-[11px] font-semibold uppercase tracking-wider text-ink-faint">GitOps</h2>

    <p v-if="error" class="mt-2 text-xs text-bad">{{ error }}</p>

    <template v-else-if="ownership">
      <p class="mt-2 text-xs font-medium" :class="headline.tone">{{ headline.label }}</p>

      <dl v-if="app" class="mt-3 space-y-2.5 text-xs">
        <div class="grid grid-cols-[8.5rem_1fr] gap-2">
          <dt class="text-ink-faint">Application</dt>
          <dd>
            <button
              class="truncate text-left text-info underline-offset-2 hover:underline"
              @click="openApplication"
            >
              {{ app.name }}
            </button>
          </dd>
        </div>
        <div v-if="app.sync || app.healthStatus" class="grid grid-cols-[8.5rem_1fr] gap-2">
          <dt class="text-ink-faint">Argo CD</dt>
          <dd class="text-ink">{{ [app.sync, app.healthStatus].filter(Boolean).join(' · ') }}</dd>
        </div>
        <div v-if="ownership.generatedBy" class="grid grid-cols-[8.5rem_1fr] gap-2">
          <dt class="text-ink-faint">Generated by</dt>
          <dd class="text-ink">
            {{ ownership.generatedBy }}
            <span class="text-ink-faint">(ApplicationSet)</span>
          </dd>
        </div>
      </dl>

      <div
        v-for="(source, index) in sources"
        :key="index"
        class="mt-3 rounded-lg border border-line px-3 py-2.5"
      >
        <p v-if="sources.length > 1" class="mb-2 text-[10px] uppercase tracking-wider text-ink-faint">
          Source {{ index + 1 }} of {{ sources.length }}
        </p>
        <dl class="space-y-2 text-xs">
          <div v-if="source.repository || source.repoUrl" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Repository</dt>
            <dd class="break-all text-ink">{{ source.repository || source.repoUrl }}</dd>
          </div>
          <div v-if="source.chart" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Chart</dt>
            <dd class="text-ink">{{ source.chart }}</dd>
          </div>
          <div v-if="source.revision" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Revision</dt>
            <dd class="font-mono text-ink">{{ source.revision }}</dd>
          </div>
          <div v-if="source.path" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Path</dt>
            <dd class="break-all font-mono text-ink">{{ source.path }}</dd>
          </div>
          <div class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Manifest</dt>
            <dd class="text-ink-muted">{{ certainty(source) }}</dd>
          </div>
        </dl>
        <p v-if="source.note" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
          {{ source.note }}
        </p>
      </div>

      <template v-if="searchable">
        <button
          class="mt-3 rounded-lg border border-line px-3 py-1.5 text-xs text-ink-muted hover:text-ink disabled:cursor-default disabled:text-ink-faint"
          :disabled="searching"
          @click="locate"
        >
          <template v-if="searching">Reading the repository…</template>
          <template v-else-if="search || searchError">Look again</template>
          <template v-else>Locate manifest</template>
        </button>

        <p v-if="searching" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
          The first read of a repository copies it, which can take a few seconds. Your own git
          credentials are used, the same as running git in a terminal.
        </p>

        <p v-else-if="searchError" class="mt-2 text-[11px] leading-relaxed text-bad">
          {{ searchError }}
        </p>

        <div v-else-if="located" class="mt-3 rounded-lg border border-line px-3 py-2.5">
          <dl class="space-y-2 text-xs">
            <div class="grid grid-cols-[7.5rem_1fr] gap-2">
              <dt class="text-ink-faint">File</dt>
              <dd class="break-all font-mono text-ink">{{ located.path }}</dd>
            </div>
            <div v-if="located.document > 0" class="grid grid-cols-[7.5rem_1fr] gap-2">
              <dt class="text-ink-faint">Document</dt>
              <dd class="text-ink">{{ located.document + 1 }} in that file</dd>
            </div>
            <div v-if="commit" class="grid grid-cols-[7.5rem_1fr] gap-2">
              <dt class="text-ink-faint">Read at</dt>
              <dd class="font-mono text-ink">{{ commit }}</dd>
            </div>
          </dl>

          <button class="mt-2 text-xs text-brand hover:underline" @click="contentOpen = !contentOpen">
            {{ contentOpen ? 'Hide manifest' : 'Show manifest' }}
          </button>

          <pre
            v-if="contentOpen"
            class="mt-2 max-h-80 overflow-auto rounded-md bg-surface-2 p-2.5 font-mono text-[11px] leading-relaxed text-ink-muted"
          >{{ located.content }}</pre>

          <p v-if="contentOpen" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
            This is what the repository says, not what the cluster is running. Nothing here writes
            back.
          </p>
        </div>

        <div v-else-if="candidates.length" class="mt-3 rounded-lg border border-line px-3 py-2.5">
          <p class="text-xs text-warn">{{ search?.reason }}</p>
          <ul class="mt-2 space-y-1">
            <li
              v-for="candidate in candidates"
              :key="`${candidate.path}:${candidate.document}`"
              class="break-all font-mono text-[11px] text-ink-muted"
            >
              {{ candidate.path
              }}<span v-if="candidate.document > 0" class="text-ink-faint">
                · document {{ candidate.document + 1 }}</span
              >
            </li>
          </ul>
          <p v-if="commit" class="mt-2 text-[11px] text-ink-faint">
            Read at <span class="font-mono">{{ commit }}</span>
          </p>
        </div>

        <p v-else-if="search" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
          {{ search.reason }}
        </p>
      </template>

      <p v-if="!managed" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
        {{ ownership.reason }}
      </p>
    </template>
  </section>
</template>
