<script setup lang="ts">
/**
 * The drawer's answer to "what does Git say this object should be, and does the
 * cluster agree?".
 *
 * The panel is written to be believed only as far as it should be. Argo CD can
 * say with certainty that it manages an object, it can say almost nothing about
 * which file in a repository declares it, and the difference between that file
 * and the running object is a third statement again. They are shown as separate
 * claims rather than blurred into one confident line.
 *
 * Source rather than desired, throughout. What this compares against is a file,
 * and a Helm rendering or a pipeline that rewrites an image may sit between that
 * file and what Argo CD applied.
 *
 * No Kubernetes knowledge lives here. Whether `replicas: 1` is a default, which
 * fields a controller owns, what to call a path — all of it is decided in Go,
 * where it can be tested, and arrives on each difference as a class, a label and
 * a reason.
 */
import { computed, onUnmounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'

import { api, copyToClipboard, message } from '@/api'
import GitAccessDiagnosis from '@/components/resource/GitAccessDiagnosis.vue'
import { useUIStore } from '@/stores/ui'
import {
  ComparisonBlocker,
  ComparisonState,
  DifferenceClass,
  DifferenceKind,
  GitRenderer,
  ManifestCertainty,
  OwnershipConfidence,
} from '@/types'
import type { GitAccess, SourceState, GitSource, ResourceOwnership, ResourceRef } from '@/types'

const props = defineProps<{ clusterId: string; resource: ResourceRef }>()

const router = useRouter()
const ui = useUIStore()

const ownership = ref<ResourceOwnership | null>(null)
const error = ref('')

const sourceState = ref<SourceState | null>(null)
const searching = ref(false)
const searchError = ref('')
const contentOpen = ref(false)
const diffOpen = ref(false)
const outputOpen = ref(false)
const copied = ref(false)

const access = ref<GitAccess | null>(null)
const diagnosing = ref(false)
const accessError = ref('')
let copiedTimer = 0

// Clicking down a list starts reads that finish out of order, and only the
// newest one is allowed to write its answer.
let token = 0

async function load() {
  const mine = ++token
  error.value = ''
  // A comparison belongs to the object it was run for. Carrying it to the next
  // row would name a file as somewhere else's source of truth.
  sourceState.value = null
  searchError.value = ''
  searching.value = false
  contentOpen.value = false
  diffOpen.value = false
  clearCopied()
  try {
    const found = await api.gitOwnership(props.clusterId, props.resource)
    if (mine !== token) return
    ownership.value = found
  } catch (err) {
    if (mine !== token) return
    error.value = message(err)
    ownership.value = null
  }
}

watch(
  () => [props.clusterId, props.resource.kind, props.resource.namespace, props.resource.name],
  load,
  { immediate: true },
)

// A cluster that does not run Argo CD has no GitOps story, and a row saying so
// on every drawer would be noise rather than news.
const shown = computed(() => ownership.value?.installed === true)

const app = computed(() => ownership.value?.app ?? null)
const sources = computed(() => ownership.value?.sources ?? [])

const managed = computed(() => {
  const confidence = ownership.value?.confidence
  return (
    confidence === OwnershipConfidence.OwnershipTracked ||
    confidence === OwnershipConfidence.OwnershipConfirmed
  )
})

/**
 * headline is the one sentence the panel leads with.
 *
 * A candidate gets its own wording rather than a quieter colour, because an
 * engineer who reads "Managed by Argo CD" will go and edit a repository, and
 * the label is the only thing standing between a guess and that edit.
 */
const headline = computed(() => {
  switch (ownership.value?.confidence) {
    case OwnershipConfidence.OwnershipTracked:
    case OwnershipConfidence.OwnershipConfirmed:
      return { label: 'Managed by Argo CD', tone: 'text-ok' }
    case OwnershipConfidence.OwnershipCandidate:
      return { label: 'Possibly managed by Argo CD', tone: 'text-warn' }
    default:
      return { label: 'Unmanaged', tone: 'text-ink-muted' }
  }
})

/** certainty puts a word on how close to a file a source gets. */
function certainty(source: GitSource): string {
  switch (source.certainty) {
    case ManifestCertainty.ManifestExact:
      return 'Manifest located'
    case ManifestCertainty.ManifestTree:
      return 'Source tree known'
    case ManifestCertainty.ManifestGenerated:
      return renderers[source.renderer] ?? `Rendered by ${source.renderer}`
    default:
      return 'No manifests'
  }
}

/**
 * renderers are the names people use for these tools, which is not what the
 * Argo CD field is spelled as. A row reading "Generated by kustomize" beside a
 * note about overlays is the machine's spelling in the place a person reads.
 *
 * A chart is not rendered from anything in Git and does not get the verb.
 */
const renderers: Partial<Record<GitRenderer, string>> = {
  [GitRenderer.RendererKustomize]: 'Rendered by Kustomize',
  [GitRenderer.RendererHelm]: 'Rendered by Helm',
  [GitRenderer.RendererPlugin]: 'Rendered by a plugin',
  [GitRenderer.RendererChart]: 'Helm chart',
}

/**
 * searchable says whether there is a file to go and look for.
 *
 * Only a directory of plain manifests has one. Helm, Kustomize and config
 * management plugins render their objects from templates, so no file in the
 * repository equals what is running, and offering a button that could only
 * come back empty would be worse than offering nothing.
 */
const searchable = computed(
  () =>
    managed.value &&
    sources.value.some((source) => source.certainty === ManifestCertainty.ManifestTree),
)

const search = computed(() => sourceState.value?.search ?? null)
const comparison = computed(() => sourceState.value?.comparison ?? null)
const located = computed(() => search.value?.located ?? null)
const candidates = computed(() => search.value?.candidates ?? [])

// What git actually said, set only when git is the thing that refused. The
// sentence shown above it is one line lifted out of this, and the lifting can
// be wrong about a failure nobody has seen yet.
const gitOutput = computed(() => search.value?.output ?? '')

// Whether the repository, rather than anything about the manifest, is what
// stopped the comparison. It is the one blocker with somewhere further to go:
// a Helm Application has no file to compare and never will, and two files
// declaring one name is a state of the repository rather than a fault in
// reaching it.
const unreachable = computed(
  () => comparison.value?.blocker === ComparisonBlocker.BlockerRepository,
)

/**
 * diagnose asks which part of the path to the repository is refusing.
 *
 * Behind a press rather than run the moment a comparison fails. It opens a
 * connection to somebody's git host, and doing that automatically would mean
 * clicking down a list of resources quietly dialled a server for every one
 * that could not be read.
 */
async function diagnose() {
  diagnosing.value = true
  accessError.value = ''
  try {
    access.value = await api.diagnoseGitAccess(props.clusterId, props.resource)
  } catch (err) {
    access.value = null
    accessError.value = message(err)
  } finally {
    diagnosing.value = false
  }
}

// Two lists rather than one filtered at render time. The whole point of the
// classification is that these are answers to different questions, and putting
// them in one list with a badge on some of them would be the flat dump again.
const meaningful = computed(() =>
  (comparison.value?.differences ?? []).filter(
    (difference) => difference.class === DifferenceClass.DifferenceMeaningful,
  ),
)
const systemManaged = computed(() =>
  (comparison.value?.differences ?? []).filter(
    (difference) => difference.class !== DifferenceClass.DifferenceMeaningful,
  ),
)

// The file name is what somebody is looking for; the directory is how to find
// it again later. Splitting them lets the name lead and the path sit under it.
const manifestName = computed(() => located.value?.path.split('/').pop() ?? '')
const manifestDirectory = computed(() => {
  const path = located.value?.path ?? ''
  const cut = path.lastIndexOf('/')
  return cut < 0 ? '' : path.slice(0, cut + 1)
})

// Seven characters is how a commit is written down and said out loud, and the
// whole hash is on the clipboard of nobody who wanted it here.
const commit = computed(() => search.value?.commit?.slice(0, 7) ?? '')

/**
 * compare reads the repository and holds the manifest against the object.
 *
 * Deliberately behind a press rather than run when the drawer opens: the first
 * read of a repository clones it, and doing that to every row somebody clicks
 * through would make the list feel broken.
 */
async function compare() {
  const mine = token
  searching.value = true
  searchError.value = ''
  contentOpen.value = false
  diffOpen.value = false
  outputOpen.value = false

  // A diagnosis describes the repository as it was a moment ago. Keeping one
  // beside a fresh comparison would let the panel show a solved problem and an
  // unsolved one at the same time and say nothing about which is which.
  access.value = null
  accessError.value = ''
  try {
    const found = await api.sourceState(props.clusterId, props.resource)
    if (mine !== token) return
    sourceState.value = found
  } catch (err) {
    if (mine !== token) return
    searchError.value = message(err)
    sourceState.value = null
  } finally {
    if (mine === token) searching.value = false
  }
}

/**
 * summary is the one line the comparison leads with.
 *
 * It counts only what the reader has to act on. The counting is the backend's,
 * not this component's: whether `replicas: 1` is a Kubernetes default is a
 * question about Kubernetes, and answering it here would put Kubernetes
 * semantics somewhere no test can reach them.
 *
 * "Unavailable" is deliberately not a failure colour. A Helm Application will
 * never have a file to compare against, and a panel that shows that in red
 * teaches people that it is broken.
 */
const summary = computed(() => {
  const result = comparison.value
  switch (result?.state) {
    case ComparisonState.ComparisonEqual:
      // Not "identical". An object carrying its own controller's annotations
      // does not match its manifest, and the wording says only what is true.
      return {
        label: result.systemManaged ? 'No meaningful differences' : 'No differences',
        tone: 'text-ok',
      }
    case ComparisonState.ComparisonDiffers:
      return {
        label: `${result.meaningful} meaningful ${
          result.meaningful === 1 ? 'difference' : 'differences'
        }`,
        tone: 'text-warn',
      }
    default:
      return { label: 'Unavailable', tone: 'text-ink-muted' }
  }
})

/**
 * disagreement fires when Argo CD and this comparison do not tell the same
 * story.
 *
 * They are allowed to disagree. Argo CD renders the source and applies its own
 * normalisation and ignore rules; this reads one file and compares fields. When
 * they differ, both facts are shown and neither is corrected, because assuming
 * one of them is wrong is how a panel starts lying.
 */
const disagreement = computed(() => {
  const sync = app.value?.sync
  const state = comparison.value?.state
  if (!sync || !state || state === ComparisonState.ComparisonUnavailable) return ''
  if (sync === 'Synced' && state === ComparisonState.ComparisonDiffers) {
    return 'Argo CD reports this Application as synced. It renders and normalises its sources differently, so the two can disagree.'
  }
  if (sync === 'OutOfSync' && state === ComparisonState.ComparisonEqual) {
    return 'Argo CD reports this Application as out of sync. The difference may be in another object it manages, or in a rule this comparison does not apply.'
  }
  return ''
})

/**
 * copySource puts the manifest on the clipboard.
 *
 * The whole document, exactly as the repository has it, because the reason to
 * copy a manifest is to paste it somewhere that has to parse it. What is on
 * screen is already the one located document rather than the whole file, so
 * there is nothing to trim here.
 *
 * The button also closes over nothing: it reads the located manifest at the
 * moment it is pressed, so a comparison that finished while somebody was
 * reaching for it cannot put the previous object's manifest on the clipboard.
 */
async function copySource() {
  const content = located.value?.content
  if (!content) return
  if (!(await copyToClipboard(content))) {
    ui.say('Could not copy to the clipboard.', 'bad')
    return
  }
  copied.value = true
  window.clearTimeout(copiedTimer)
  copiedTimer = window.setTimeout(clearCopied, 1500)
}

function clearCopied() {
  window.clearTimeout(copiedTimer)
  copied.value = false
}

onUnmounted(clearCopied)

/**
 * side says where a one-sided difference lives.
 *
 * "Only in the cluster" and no more. Whether it got there by drift, by a
 * webhook or by a controller is not something this comparison can know, and a
 * card that said "someone changed the cluster" would be inventing a culprit.
 */
function side(kind: DifferenceKind): string {
  switch (kind) {
    case DifferenceKind.DifferenceAddedInLive:
      return 'Only in the cluster'
    case DifferenceKind.DifferenceMissingInLive:
      return 'Only in the source'
    default:
      return ''
  }
}

function openApplication() {
  const target = app.value
  const kind = ownership.value?.appKind
  if (!target || !kind) return
  void router.push({
    name: 'resource',
    params: {
      clusterId: props.clusterId,
      kind,
      // "_" stands in for "no namespace": a cluster-scoped object still needs
      // a path segment.
      namespace: target.namespace || '_',
      name: target.name,
    },
  })
}
</script>

<template>
  <section v-if="shown || error">
    <h2 class="text-[11px] font-semibold uppercase tracking-wider text-ink-faint">GitOps</h2>

    <p v-if="error" class="mt-2 text-xs text-bad">{{ error }}</p>

    <template v-else-if="ownership">
      <p class="mt-2 text-xs font-medium" :class="headline.tone">{{ headline.label }}</p>

      <dl v-if="app" class="mt-3 space-y-2.5 text-xs">
        <div class="grid grid-cols-[8.5rem_1fr] gap-2">
          <dt class="text-ink-faint">Application</dt>
          <dd>
            <button
              class="truncate text-left text-info underline-offset-2 hover:underline"
              @click="openApplication"
            >
              {{ app.name }}
            </button>
          </dd>
        </div>
        <div v-if="app.sync || app.healthStatus" class="grid grid-cols-[8.5rem_1fr] gap-2">
          <dt class="text-ink-faint">Argo CD</dt>
          <dd class="text-ink">{{ [app.sync, app.healthStatus].filter(Boolean).join(' · ') }}</dd>
        </div>
        <div v-if="ownership.generatedBy" class="grid grid-cols-[8.5rem_1fr] gap-2">
          <dt class="text-ink-faint">Generated by</dt>
          <dd class="text-ink">
            {{ ownership.generatedBy }}
            <span class="text-ink-faint">(ApplicationSet)</span>
          </dd>
        </div>
      </dl>

      <div
        v-for="(source, index) in sources"
        :key="index"
        class="mt-3 rounded-lg border border-line px-3 py-2.5"
      >
        <p v-if="sources.length > 1" class="mb-2 text-[10px] uppercase tracking-wider text-ink-faint">
          Source {{ index + 1 }} of {{ sources.length }}
        </p>
        <dl class="space-y-2 text-xs">
          <div v-if="source.repository || source.repoUrl" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Repository</dt>
            <dd class="break-all text-ink">{{ source.repository || source.repoUrl }}</dd>
          </div>
          <div v-if="source.chart" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Chart</dt>
            <dd class="text-ink">{{ source.chart }}</dd>
          </div>
          <div v-if="source.revision" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Revision</dt>
            <dd class="font-mono text-ink">{{ source.revision }}</dd>
          </div>
          <div v-if="source.path" class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Path</dt>
            <dd class="break-all font-mono text-ink">{{ source.path }}</dd>
          </div>
          <div class="grid grid-cols-[7.5rem_1fr] gap-2">
            <dt class="text-ink-faint">Manifest</dt>
            <dd class="text-ink-muted">{{ certainty(source) }}</dd>
          </div>
        </dl>
        <p v-if="source.note" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
          {{ source.note }}
        </p>
      </div>

      <template v-if="searchable">
        <button
          class="mt-3 rounded-lg border border-line px-3 py-1.5 text-xs text-ink-muted hover:text-ink disabled:cursor-default disabled:text-ink-faint"
          :disabled="searching"
          @click="compare"
        >
          <template v-if="searching">Reading the repository…</template>
          <template v-else-if="sourceState || searchError">Compare again</template>
          <template v-else>Compare with Git</template>
        </button>

        <p v-if="searching" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
          The first read of a repository copies it, which can take a few seconds. Your own git
          credentials are used, the same as running git in a terminal.
        </p>

        <p v-else-if="searchError" class="mt-2 text-[11px] leading-relaxed text-bad">
          {{ searchError }}
        </p>

        <div v-else-if="located" class="mt-3 rounded-lg border border-line px-3 py-2.5">
          <!--
            Where the file is, said quietly. It matters for reproducibility and
            it is not what somebody opened this panel to find out, so it leads
            with the file name and puts the directory and the commit under it
            at the size of a footnote.
          -->
          <p class="text-[10px] uppercase tracking-wider text-ink-faint">Source</p>
          <p class="mt-1 break-all font-mono text-xs text-ink">{{ manifestName }}</p>
          <p class="mt-0.5 break-all font-mono text-[10px] text-ink-faint">
            {{ manifestDirectory }}<span v-if="commit"> @ {{ commit }}</span>
            <span v-if="located.document > 0"> · document {{ located.document + 1 }}</span>
          </p>

          <div v-if="comparison" class="mt-3 border-t border-line pt-3">
            <p class="text-[10px] uppercase tracking-wider text-ink-faint">Source vs Live</p>
            <p class="mt-1 text-xs font-medium" :class="summary.tone">{{ summary.label }}</p>

            <p v-if="disagreement" class="mt-1.5 text-[11px] leading-relaxed text-ink-faint">
              {{ disagreement }}
            </p>

            <ul v-if="meaningful.length" class="mt-2.5 space-y-2">
              <li
                v-for="difference in meaningful"
                :key="difference.path"
                class="rounded-md bg-surface-2 px-2.5 py-2"
              >
                <p class="text-[11px] font-medium text-ink">
                  {{ difference.label || difference.path }}
                </p>
                <p
                  v-if="difference.label && difference.subject"
                  class="break-all font-mono text-[10px] text-ink-faint"
                >
                  {{ difference.subject }}
                </p>

                <p v-if="difference.redacted" class="mt-1.5 text-[11px] text-ink-muted">
                  Value differs. This kind's values are not shown here.
                </p>

                <template v-else-if="side(difference.kind)">
                  <p class="mt-1.5 text-[10px] uppercase tracking-wider text-ink-faint">
                    {{ side(difference.kind) }}
                  </p>
                  <p class="break-all font-mono text-[11px] text-ink-muted">
                    {{ difference.source || difference.live }}
                  </p>
                </template>

                <template v-else>
                  <p class="mt-1.5 text-[10px] uppercase tracking-wider text-ink-faint">Source</p>
                  <p class="break-all font-mono text-[11px] text-ink-muted">
                    {{ difference.source }}
                  </p>
                  <p class="mt-1 text-[10px] uppercase tracking-wider text-ink-faint">Live</p>
                  <p class="break-all font-mono text-[11px] text-ink-muted">{{ difference.live }}</p>
                </template>
              </li>
            </ul>

            <!--
              Kept, not discarded. Somebody working out why a rollout happened
              wants the revision annotation, and it is one press away.
            -->
            <template v-if="systemManaged.length">
              <button
                class="mt-2.5 text-xs text-brand hover:underline"
                @click="diffOpen = !diffOpen"
              >
                {{ diffOpen ? 'Hide' : 'Show' }} {{ systemManaged.length }} system-managed
                {{ systemManaged.length === 1 ? 'difference' : 'differences' }}
              </button>

              <ul v-if="diffOpen" class="mt-2 space-y-1.5">
                <li
                  v-for="difference in systemManaged"
                  :key="difference.path"
                  class="rounded-md bg-surface-2 px-2.5 py-1.5"
                >
                  <p class="text-[11px] text-ink-muted">
                    {{ difference.label || difference.path }}
                    <span v-if="difference.subject" class="break-all font-mono text-[10px]">
                      {{ difference.subject }}
                    </span>
                  </p>
                  <p v-if="!difference.redacted" class="break-all font-mono text-[11px] text-ink">
                    {{ difference.live || difference.source }}
                  </p>
                  <p v-if="difference.reason" class="mt-0.5 text-[10px] text-ink-faint">
                    {{ difference.reason }}
                  </p>
                </li>
              </ul>
            </template>
          </div>

          <button
            class="mt-2.5 block text-xs text-brand hover:underline"
            @click="contentOpen = !contentOpen"
          >
            {{ contentOpen ? 'Hide source YAML' : 'View source YAML' }}
          </button>

          <!--
            The copy sits on the manifest rather than beside the disclosure that
            opens it. A button next to "View source YAML" has to say what it
            copies; one in the corner of the thing itself does not.
          -->
          <div v-if="contentOpen" class="relative mt-2">
            <pre
              class="max-h-80 overflow-auto rounded-md bg-surface-2 py-2.5 pl-2.5 pr-10 font-mono text-[11px] leading-relaxed text-ink-muted"
            >{{ located.content }}</pre>

            <button
              class="absolute right-1.5 top-1.5 rounded-md border border-line bg-surface-2 p-1.5 hover:text-ink"
              :class="copied ? 'text-ok' : 'text-ink-faint'"
              :title="copied ? 'Copied' : 'Copy this manifest'"
              :aria-label="copied ? 'Copied' : 'Copy this manifest'"
              @click="copySource"
            >
              <svg
                v-if="copied"
                viewBox="0 0 16 16"
                class="size-3.5"
                fill="none"
                aria-hidden="true"
              >
                <path
                  d="M3.4 8.4 6.4 11.4 12.6 5.2"
                  stroke="currentColor"
                  stroke-width="1.4"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <svg v-else viewBox="0 0 16 16" class="size-3.5" fill="none" aria-hidden="true">
                <rect
                  x="5.6"
                  y="5.6"
                  width="7.9"
                  height="7.9"
                  rx="1.6"
                  stroke="currentColor"
                  stroke-width="1.2"
                />
                <path
                  d="M10.4 5.6V4a1.6 1.6 0 0 0-1.6-1.6H4A1.6 1.6 0 0 0 2.4 4v4.8A1.6 1.6 0 0 0 4 10.4h1.6"
                  stroke="currentColor"
                  stroke-width="1.2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>
          </div>

          <p v-if="contentOpen" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
            This is what the repository says, not what the cluster is running, and not necessarily
            what Argo CD applied — a rendering step or a pipeline may sit between them. Nothing here
            writes back.
          </p>
        </div>

        <div v-else-if="candidates.length" class="mt-3 rounded-lg border border-line px-3 py-2.5">
          <p class="text-xs text-warn">{{ search?.reason }}</p>
          <ul class="mt-2 space-y-1">
            <li
              v-for="candidate in candidates"
              :key="`${candidate.path}:${candidate.document}`"
              class="break-all font-mono text-[11px] text-ink-muted"
            >
              {{ candidate.path
              }}<span v-if="candidate.document > 0" class="text-ink-faint">
                · document {{ candidate.document + 1 }}</span
              >
            </li>
          </ul>
          <p v-if="commit" class="mt-2 text-[11px] text-ink-faint">
            Read at <span class="font-mono">{{ commit }}</span>
          </p>
        </div>

        <template v-else-if="search">
          <p class="mt-2 text-[11px] leading-relaxed text-ink-faint">{{ search.reason }}</p>

          <!--
            A repository that could not be read is the one refusal with
            somewhere further to go. The others describe the repository
            accurately — a Helm Application has no file to compare and never
            will — and offering to diagnose them would send somebody looking
            for a fault that is not there.
          -->
          <button
            v-if="unreachable && !access"
            class="mt-2 rounded-lg border border-line px-2.5 py-1 text-[11px] text-ink-muted hover:text-ink disabled:cursor-default disabled:text-ink-faint"
            :disabled="diagnosing"
            @click="diagnose"
          >
            {{ diagnosing ? 'Checking…' : 'Diagnose Git access' }}
          </button>

          <p v-if="accessError" class="mt-2 text-[11px] leading-relaxed text-bad">
            {{ accessError }}
          </p>

          <GitAccessDiagnosis
            v-if="access"
            class="mt-3"
            :cluster-id="clusterId"
            :resource="resource"
            :access="access"
            @retry="compare"
          />

          <!--
            The sentence above is one line lifted out of everything git wrote,
            by a rule that only knows the failures git had already grown. When
            it lifts the wrong line the reader is left arguing with a summary
            of something they cannot see, so the output it came from is one
            press away. The diagnosis carries its own copy, so this is only
            here while there is no diagnosis to read it in.
          -->
          <template v-if="gitOutput && !access">
            <button
              class="mt-2 block text-[11px] text-ink-faint underline decoration-line underline-offset-2 hover:text-ink-muted"
              @click="outputOpen = !outputOpen"
            >
              {{ outputOpen ? 'Hide git output' : 'Show git output' }}
            </button>
            <pre
              v-if="outputOpen"
              class="mt-2 max-h-60 overflow-auto whitespace-pre-wrap break-all rounded-md bg-surface-2 p-2.5 font-mono text-[11px] leading-relaxed text-ink-muted"
              >{{ gitOutput }}</pre
            >
          </template>
        </template>
      </template>

      <p v-if="!managed" class="mt-2 text-[11px] leading-relaxed text-ink-faint">
        {{ ownership.reason }}
      </p>
    </template>
  </section>
</template>
